### ISSUE TITLE
Speaker predict training problem

### ISSUE THREAD

**Issue by 980202006** [Labmem-Zhouyx/CDFSE_FastSpeech2#2]
I reproduced the cdfse model myself, but encountered the problem that the speaker classifer training does not converge. I replaced my own module with your cdfse module, but it still does not converge, and the predicted speakers all point to the same speaker. Do you have any suggestions please?

**Comment by Labmem-Zhouyx** [comment]
Hello, thanks for focusing on this work. I'm sorry haven't met this problem before.

1. How many speakers (or which dataset) did you use? 
In AISHELL-3, there are 218 speakers (We mixed the original train and test sets, and re-divided them into seen and unseen sets according to the speaker).   Each speaker has about 400 utterances.   So I think it is not difficult to train the speaker classifier on this dataset. 

2. The "use_spkcls" in configs/model.yaml should be set to True, and the “weight: cls” should be greater than 0.   You can check them and confirm whether this loss is added to the total loss (model/loss.py).
 
If it can't be solved. You can share your loss curve here. :)

**Comment by 980202006** [comment]
Thank you, I found out that the reason is that my speaker is misplaced, I have restarted training, I expect results in a few days, I can share with you
